services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: voting
      POSTGRES_PASSWORD: voting
      POSTGRES_DB: votingdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - voting-net

  api:
    build: ./api
    # Remove container_name to allow scaling (Docker handles naming with suffixes)
    environment:
      JWT_SECRET: supersecret
      DATABASE_URL: postgresql://voting:voting@postgres:5432/votingdb
      # SMTP Configuration for Real Emails
      # Replace these with your actual details
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: mathushanmaheswaran4@gmail.com
      SMTP_PASS: cniy jagw cjvk suyp
    # No ports exposed directly from API replicas
    depends_on:
      - postgres
    volumes:
      - ./api/src:/app/src
    deploy:
      replicas: 3
    networks:
      - voting-net

  loadbalancer:
    image: nginx:alpine
    container_name: loadbalancer
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - voting-net

volumes:
  db_data:

networks:
  voting-net:
    driver: bridge
